
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: orion@123
      POSTGRES_DB: ecommercedb
    ports:
      - "55432:5432"

  e-com-backend:
    build:
      context: ../../..
      dockerfile: ops/docker/dev/Dockerfile.e-com-backend
    ports:
      - "5109:8080"
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://*:8080

  # e-com-frontend:
  #   build:
  #     context: ../../..
  #     dockerfile: ops/docker/dev/Dockerfile.e-com-frontend
  #   ports:
  #     - "5032:8080"
  #   depends_on:
  #     - e-com-backend
  #   environment:
  #     ASPNETCORE_ENVIRONMENT: Development
  #     ASPNETCORE_URLS: http://*:8080

  e-com-dbupdate:
    build:
      context: ../../..
      dockerfile: ops/docker/dev/Dockerfile.e-com-dbupdater
    depends_on:
      - db
      - e-com-backend
    volumes:
      - ../../src/ProjectMainApp:/src/ProjectMainApp