
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: orion@123
      POSTGRES_DB: ecommercedb
    ports:
      - "55432:5432"

  backend:
    build:
      context: ../../..
      dockerfile: ops/docker/dev/Dockerfile.backend
    ports:
      - "5001:8081"
      - "5000:500"
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://*:5000

  # frontend:
  #   build:
  #     context: ../../..
  #     dockerfile: ops/docker/dev/Dockerfile.frontend
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend

  dbupdate:
    build:
      context: ../../..
      dockerfile: ops/docker/dev/Dockerfile.dbupdater
    depends_on:
      - db
      - backend
    #volumes:
    #  - ../../src/mainapp/BoooksMainApp:/src/BoooksMainApp