FROM mcr.microsoft.com/dotnet/sdk:9.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src

COPY src/ProjectMainApp ./ProjectMainApp/

WORKDIR /src/ProjectMainApp/Project.Endpoint
RUN dotnet restore
RUN dotnet publish Project.Endpoint.csproj -c Release --output /app/publish

FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .
COPY ops/docker/e-com-backend-entrypoint.sh /app/e-com-backend-entrypoint.sh

RUN apt-get update && apt-get install -y dos2unix && \
    dos2unix /app/e-com-backend-entrypoint.sh && \
    chmod +x /app/e-com-backend-entrypoint.sh

# ENTRYPOINT ["./e-com-backend-entrypoint.sh"]
ENTRYPOINT ["/bin/sh", "/app/e-com-backend-entrypoint.sh"]
