FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY src/ProjectMainApp ./ProjectMainApp/

WORKDIR /src/ProjectMainApp/Project.Web
RUN dotnet restore
RUN dotnet publish Project.Web.csproj -c Release --output /app/publish

FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .
#COPY ops/docker/e-com-frontend-entrypoint.sh /app/e-com-frontend-entrypoint.sh

RUN apt-get update && \
    apt-get install -y curl && \
    rm -rf /var/lib/apt/lists/*


#ENTRYPOINT ["/bin/sh", "/app/e-com-frontend-entrypoint.sh"]
ENTRYPOINT ["dotnet", "Project.Web.dll"]